name: branch Deploy
# fixed syntax error
on:
  push:
    branches:
      - '10-Code-guru'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build

        run: |
          npm install
          npm run build

      - name: Create deployment package
        run: |
          zip -r deploy.zip . -x '*.git*' 'node_modules/**' '*.github*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_ANDERS }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_ANDERS }}
          application_name: cicd-7
          environment_name: Cicd-7-env
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
          wait_for_deployment: true
