# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"  # Replace with your AWS region

      # Step 3: Zip the application files
      - name: Zip application files
        run: zip -r deploy.zip . -x "*.git*"

      # Step 4: Upload application to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "cicd-team-1"       # Replace with your Elastic Beanstalk application name
          environment_name: "e-b3y2aw3aqm"       # Replace with your Elastic Beanstalk environment name
          version_label: "v${{ github.run_number }}"    # Optional version label
          deployment_package: "deploy.zip"              # The zipped file created in the previous step

      # Optional Step 5: Notify on deployment success or failure
      - name: Notify Success
        if: success()
        run: echo "Deployment to Elastic Beanstalk successful!"

      - name: Notify Failure
        if: failure()
        run: echo "Deployment to Elastic Beanstalk failed!"
